version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=candidates
    volumes:
      - candidates_data:/var/lib/postgresql/data

volumes:
  candidates_data:
