version: '3.8'

services:
  api-gateway:
    build: ./rocaleda-api-gateway
    environment:
      - CANDIDATES_MS=candidates:8000
    ports:
      - "8000:8000"
  candidates:
    build: ./rocaleda-candidates-ms
    environment:
      - DB_URL=postgresql://docker:docker@db:5432/candidates
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=candidates
    volumes:
      - candidates_data:/var/lib/postgresql/data

volumes:
  candidates_data:
